project:
  type: website
  output-dir: docs

website:
  title: "Ruminant Palaeogenomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - group.qmd
      - research.qmd
      - contact.qmd
      - opportunities.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

