project:
  type: website
  output-dir: docs

website:
  title: "Ruminant Palaeogenomics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - group.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

