---
title: "Opportunities"
editor: 
  markdown: 
    wrap: sentence
---
## **Come work with me!**

If you are interested in joining a recently-formed group and studying the evolution and dynamics of ancient domesticates with palaeogenomics - come work with me!

For those interested in writing a funding application for PhD (i.e. IRC) or postdoctoral funds (i.e. MCRA), please email me at kevin.daly[at]ucd.ie.

And I am currently recruiting a PhD student - see below.

#### **Funded PhD Project (European/UK/International Students)**

A UCD-funded 4 year PhD for EU, UK and international applicants is available in the School of Agriculture and Food Science, University College Dublin, Ireland. The project will investigate the genetic histories of ancient small ruminants (goat and sheep), the origins of zoonotic pathogens, and how they relate to the genomic health of herds in the deep past. 

The position includes a student stipend of €22,000 per annum for the course of the PhD and postgraduate fees will be covered. A flexible start date within Q3/Q4 of 2024 is possible.

**Context:**
Genetic analysis from ancient animal remains has revealed the dynamics of the early domestication process (e.g. Daly et al 2018; Daly et al, 2021; Librado et al, 2021; Verdugo et al, 2019). However, little is known about the genomic health of domesticates - the reduction in genetic diversity which may have occurred during domestication and its possible consequences to animal health. 

Similarly, ancient genomic analysis has begun to shed light on the genetic history of human pathogens, including some zoonotic agents (e.g. Key et al, 2020), but how such zoonoses evolved with their domestic animal hosts is unknown. We are only now beginning to understand how livestock pathogens themselves evolved (Fiddaman et al, 2023), showing the power of palaeogenomic approachs to reveal disease evolution.

The project will generate sequencing data from a diverse range of sheep and goat archaeological remains over the last 10,000 years. Recovered DNA from both host and pathogen sources will be used to reconstruct genomes and chart the interlinked evolution and genetic flux of domestic ruminants and their zoonotic pathogens. The project will involve drawing from multiple disciplines and lines of evidence including genomics, microbial/pathogen evolution, archaeology and zooarchaeology, zoology/veterinary science; a flexible approach and openness to working in multiple disciplines is expected.

The trainee will be mentored by [Dr. Kevin Daly](https://scholar.google.com/citations?user=N--aZF8AAAAJ&hl=en). The successful candidate will have opportunities to collaborate with other palaeogenomic groups and present at international training courses and academic conferences.

A background in any of the following is preferred: biology, genetics & genomics, domestication, population genetics, animal genomics, microbial genetics, bioinformatics, mathematical biology, archaeology. Programming and bioinformatic experience (e.g. Linux environment, R) is an advantage but not essential; training in bioinformatics, data analysis and population genomics will be available for the student. 

Interested candidates with at least a 2.1 undergraduate degree or international equivalent can submit their CV, two letters of recommendation or references, to kevin.daly[at]ucd.ie.

The deadline for application is **7th June 2024**.


**References**

[Daly et al, 2018, "Ancient goat genomes reveal mosaic domestication in the Fertile Crescent", Science](https://www.science.org/doi/10.1126/science.aas9411)

[Daly et al, 2021, “Herded and hunted goat genomes from the dawn of domestication in the Zagros Mountains”, PNAS](https://www.pnas.org/doi/10.1073/pnas.2100901118)

[Librado et al, 2021, “The origins and spread of domestic horses from the Western Eurasian steppes”, Nature](https://www.nature.com/articles/s41586-021-04018-9)

[Verdugo et al, 2019, “Ancient cattle genomics, origins, and rapid turnover in the Fertile Crescent”, Science](https://www.science.org/doi/10.1126/science.aav1002)

[Key et al, 2020, “Emergence of human-adapted Salmonella enterica is linked to the Neolithization process”, Nature Ecology & Evolution](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7186082/)

[Fiddaman et al, 2023, "Ancient chicken remains reveal the origins of virulence in Marek’s disease virus", Science](https://www.science.org/doi/10.1126/science.adg2238)
